# Generated by Django 4.1.7 on 2023-03-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_note_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date_created',
        ),
        migrations.AddField(
            model_name='note',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
